tap "buo/cask-upgrade"
tap "cloudfoundry/tap"
tap "goreleaser/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "kong/kong"
tap "mongodb/brew"
tap "mtslzr/marmaduke-chromium"
tap "openresty/brew"
tap "osx-cross/avr"
tap "shopify/shopify"
tap "vitorgalvao/tiny-scripts"
brew "ack"
brew "adns"
brew "arduino-cli"
brew "astyle"
brew "gettext"
brew "python@3.9"
brew "glib"
brew "atk"
brew "autoconf"
brew "automake"
brew "awscli"
brew "python@3.10"
brew "azure-cli"
brew "bison"
brew "icu4c"
brew "bzip2"
brew "cabal-install"
brew "pkg-config"
brew "coreutils"
brew "unbound"
brew "jansson"
brew "cask"
brew "circleci"
brew "cmake"
brew "cowsay"
brew "libssh2"
brew "openldap"
brew "curl"
brew "docker-compose"
brew "docutils"
brew "docx2txt"
brew "dos2unix"
brew "exercism"
brew "gobject-introspection"
brew "harfbuzz"
brew "lame"
brew "libass"
brew "libsodium"
brew "tesseract"
brew "ffmpeg"
brew "flex"
brew "portaudio"
brew "fluid-synth"
brew "freetds"
brew "fzf"
brew "gcc"
brew "geos"
brew "hdf5"
brew "krb5"
brew "libxml2"
brew "libdap"
brew "libpq"
brew "numpy"
brew "poppler-qt5"
brew "gdal"
brew "gdk-pixbuf"
brew "geoip"
brew "ghostscript"
brew "git"
brew "git-lfs"
brew "gsettings-desktop-schemas"
brew "glib-networking"
brew "go"
brew "glide"
brew "gnupg"
brew "pango"
brew "gnuplot"
brew "gox"
brew "gradle"
brew "grafana", restart_service: true
brew "librsvg"
brew "graphviz"
brew "grc"
brew "groff"
brew "gstreamer"
brew "gst-plugins-base"
brew "libnice"
brew "gst-plugins-bad"
brew "gtk+3"
brew "libsoup"
brew "gst-plugins-good"
brew "gst-plugins-ugly"
brew "handbrake"
brew "htop"
brew "hub"
brew "hugo"
brew "influxdb", restart_service: true
brew "intltool"
brew "iperf"
brew "jemalloc"
brew "jq"
brew "kotlin"
brew "launch_socket_server", restart_service: true
brew "launchdns"
brew "lcov"
brew "libdvdcss"
brew "libproxy"
brew "llvm"
brew "mas"
brew "md5sha1sum", link: false
brew "media-info"
brew "memcached", restart_service: true
brew "mercurial"
brew "meson"
brew "minikube"
brew "qt"
brew "mkvtoolnix"
brew "node@14"
brew "mongosh"
brew "mysql", restart_service: true
brew "nghttp2"
brew "nginx"
brew "nmap"
brew "node-build"
brew "nodeenv"
brew "nodenv"
brew "openssl@3"
brew "p7zip"
brew "pandoc"
brew "pidof"
brew "pinentry-mac"
brew "pmd"
brew "poppler"
brew "postgresql", restart_service: true
brew "postgis"
brew "potrace"
brew "pulseaudio"
brew "py2cairo"
brew "py3cairo"
brew "pyenv"
brew "pyenv-virtualenv"
brew "pygobject3"
brew "ragel"
brew "ruby-build"
brew "rbenv"
brew "redis", restart_service: true
brew "resty", link: false
brew "ruby"
brew "rustup-init"
brew "s3cmd"
brew "scipy"
brew "sdl"
brew "shairport-sync"
brew "socat"
brew "softhsm"
brew "squashfs"
brew "swiftformat"
brew "telegraf", restart_service: true
brew "telnet"
brew "the_silver_searcher"
brew "tree"
brew "vala"
brew "wget"
brew "yarn"
brew "yt-dlp"
brew "zlib"
brew "zsh"
brew "zsh-completions"
brew "goreleaser/tap/goreleaser"
brew "heroku/brew/heroku"
brew "mongodb/brew/mongodb-community"
brew "shopify/shopify/toxiproxy"
brew "vitorgalvao/tiny-scripts/cask-repair"
cask "1password"
cask "1password-cli"
cask "araxis-merge"
cask "atom"
cask "brave-browser"
cask "docker"
cask "dotnet"
cask "dropbox"
cask "encryptme"
cask "epub-to-pdf"
cask "flux"
cask "font-fira-code"
cask "google-chrome"
cask "google-cloud-sdk"
cask "gpg-suite"
cask "graphiql"
cask "handbrake"
cask "insomnia"
cask "licecap"
cask "makemkv"
cask "marmaduke-chromium"
cask "mysqlworkbench"
cask "ngrok"
cask "pgadmin4"
cask "skype"
cask "snagit"
cask "spotify"
cask "sublime-text"
cask "transmission"
cask "viscosity"
cask "visual-studio-code"
cask "vlc"
cask "vmware-fusion"
cask "wkhtmltopdf"
cask "xquartz"
mas "Amphetamine", id: 937984704
mas "Cyberduck", id: 409222199
mas "Developer", id: 640199958
mas "GarageBand", id: 682658836
mas "GIF Brewery 3", id: 1081413713
mas "Hex Fiend", id: 1342896380
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "Microsoft Word", id: 462054704
mas "NordVPN IKE", id: 1116599239
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Scrivener", id: 1310686187
mas "Simple Comic", id: 1497435571
mas "Slack", id: 803453959
mas "Textual IRC Client", id: 1262957439
mas "Xcode", id: 497799835
