tap 'github/bootstrap'

brew 'astyle'
brew 'autoconf'
brew 'cmake'
brew 'git'
brew 'git-lfs'
brew 'gnupg'
brew 'gpg-agent'
brew 'grc'
brew 'heroku'
brew 'imagemagick'
brew 'jemalloc'
brew 'jq'
brew 'mas'
brew 'nginx'
brew 'node'
brew 'nodenv'
brew 'pcre'
brew 'pinentry-mac'
brew 'pkg-config'
brew 'rbenv'
brew 'rust'
brew 'the_silver_searcher'
brew 'valgrind'
brew 'zsh'
brew 'zsh-completions'

cask '1password'
cask 'araxis-merge'
cask 'atom'
cask 'cloak'
cask 'dropbox'
cask 'firefox'
cask 'flux'
cask 'font-fira-code'
cask 'gimp'
cask 'google-chrome'
cask 'handbrake'
cask 'licecap'
cask 'screenhero'
cask 'spotify'
cask 'sublime-text'
cask 'transmission'
cask 'vlc'

mas 'Cyberduck', id: 409222199
mas 'Slack', id: 803453959
mas 'Textual', id: 896450579
