#!/usr/bin/env bash
#
# bootstrap installs things.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

echo ''

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

setup_strap () {
  STRAP_GIT_NAME="Garen J. Torikian"
  STRAP_GIT_EMAIL="gjtorikian@gmail.com"
  STRAP_GITHUB_USER="gjtorikian"

  success 'set up strap 😎'
}


# Check for Homebrew
if test ! $(which brew)
then
  restart=true
fi

setup_strap

STRAP_GITHUB_TOKEN=$(cat passwordz/strap_token)
cd script
git clone https://github.com/MikeMcQuaid/strap
cd ..
bash script/strap/bin/strap.sh
