#!/usr/bin/env bash
#
# bootstrap installs things.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

echo ''

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

setup_strap () {
  STRAP_GIT_NAME="Garen J. Torikian"
  STRAP_GIT_EMAIL="gjtorikian@gmail.com"
  STRAP_GITHUB_USER="gjtorikian"

  success 'set up strap 😎'
}

setup_gitconfig () {
  if ! [ -f git/gitconfig.local.symlink ]
  then
    info 'setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    sed -e "s/AUTHORNAME/$STRAP_GIT_NAME/g" -e "s/AUTHOREMAIL/$STRAP_GIT_EMAIL/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink

    success 'gitconfig'
  fi
}

link_file () {
  local src=$1 dst=$2

  local overwrite= backup= skip=
  local action=

  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

      local currentSrc="$(readlink $dst)"

      if [ "$currentSrc" == "$src" ]
      then

        skip=true;

      else

        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac

      fi

    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      success "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      success "skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    success "linked $1 to $2"
  fi
}

install_dotfiles () {
  info 'installing dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done

  mkdir -p "$HOME/.ssh"
  link_file "$DOTFILES_ROOT/system/ssh.config" "$HOME/.ssh/config"
}

# Check for Homebrew
if test ! $(which brew)
then
  restart=true
fi

setup_strap

if [ "$restart" = true ] ; then
  STRAP_GITHUB_TOKEN=$(cat passwordz/strap_token)
  bash script/strap
  info "I need to restart now. Run this script again when everything comes back."
  sleep 5
  sudo shutdown -r now
else
  info "Skipping strap because it was done!"
fi

brew bundle

setup_gitconfig
install_dotfiles

sudo xcodebuild -license accept
brew link gnupg

# find the installers and run them iteratively
for installer in $(find . -name "*install.sh"); do
  sh -c "${installer}"
done

bin/vscode-install

fish/install.sh

macos/setup.sh

background="$HOME/.dotfiles/background/current.jpg"
osascript -e "tell application \"Finder\" to set desktop picture to POSIX file \"$background\""

echo ''
echo '  All installed!'
